### ISSUE TITLE
[SG REQUEST] Lint in my belly button

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#112]
### SG Request YAML

- business_justification: >
    Create SG for Datadog VPC endpoint, its smelly
  thirdpartyName: Datadog
  thirdpartyId: 1234567
  accountId: 6666666
  vpcId: vpc-0123456789abcdef0
  region: us-west-2

**Comment by drewpypro** [comment]
### ⚠️ yamllint found issues in your submitted YAML

```txt
/tmp/issue.yaml:1:1: [error] too many blank lines (1 > 0) (empty-lines)
/tmp/issue.yaml:9:1: [error] too many blank lines (1 > 0) (empty-lines)
```

<details><summary>📄 Full YAML</summary>

```yaml

- business_justification: >
    Create SG for Datadog VPC endpoint, its smelly
  thirdpartyName: Datadog
  thirdpartyId: 1234567
  accountId: 6666666
  vpcId: vpc-0123456789abcdef0
  region: us-west-2

```
</details>
