### ISSUE TITLE
[SG REQUEST] Lint in my belly button

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#114]
### SG Request YAML

```yaml
- business_justification: >
    Lint in my smelly button
  thirdpartyName: Datadog
  thirdpartyId: 1234567
  accountId: 6666666
  vpcId: vpc-0123456789abcdef0
  region: us-west-2
```

**Comment by drewpypro** [comment]
### ⚠️ yamllint found issues in your submitted YAML

```txt
/tmp/issue.yaml:1:1: [error] too many blank lines (1 > 0) (empty-lines)
/tmp/issue.yaml:2:1: [error] syntax error: found character '`' that cannot start any token (syntax)
```

<details><summary>📄 Full YAML</summary>

```yaml

```yaml
- business_justification: >
    Lint in my smelly button
  thirdpartyName: Datadog
  thirdpartyId: 1234567
  accountId: 6666666
  vpcId: vpc-0123456789abcdef0
  region: us-west-2
```
```
</details>
