### ISSUE TITLE
[SG REQUEST] <ThirdPartyName> in <region>

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#126]
### SG Request YAML

```yaml
- request_id REQ123456
  business_justification: >
    Create SG for Datadog VPC endpoint
  thirdpartyName: Datadog
  thirdpartyId: 1234567
  accountId: 6666666
  vpcId: vpc-0123456789abcdef0
  region: us-west-2
```
