### ISSUE TITLE
[ACCESS REQUEST] Successful Lint and Schema Validation Test

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#139]
### Access Rule YAML

```yaml
- request_id:
  business_justification: >
    <Provide detailed justification here> 
  source:
    account_id: 
    vpc_id: 
    region: 
    security_group_ids:
    ips: ["1.1.1.1/32"]
  destination:
    account_id: 12345678
    vpc_id: vpc-0c9a555406867d5da
    region: "us-west-2"
    security_group_ids:
    - sg-0b5d6e2811145808d
    ips: []
  protocol: tcp
  port: 443
  appid: 
  url:  
  enable_palo_inspection: false
```
