### ISSUE TITLE
[SG REQUEST] Testing auto-approve

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#153]
### SG Request YAML

```yaml
- request_id: REQ123456
  business_justification: >
    Create SG for Drewdog1 VPC endpoint
  thirdpartyName: Drewdog1
  thirdpartyId: 1234567
  accountId: 6666666
  vpc_id: vpc-0123456789abcdef0
  region: us-west-2
```
