### ISSUE TITLE
[SG REQUEST] Testing New Security-Group Output Test

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#159]
### SG Request YAML

```yaml
- request_id: REQ123456
  business_justification: >
    Create SG for Test33 VPC endpoint
  thirdpartyName: Test33
  thirdpartyId: 1234567
  accountId: 6666666
  vpc_id: vpc-0c9a555406867d5da
  region: us-west-2
```
