### ISSUE TITLE
[SG] Create PrivateLink Consumer for: drewdog

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#176]
### AWS Region

us-east-1

### VPC ID

vpc-0f0330876868cc9d2 (us-east-1)

### Third-Party Name

drewdog

### Third-Party ID

555666

### VPC Endpoint Service Name

com.amazonaws.vpce.us-east-1.vpce-svc-064easdr23423423

### Request ID

RQ-005

### Business Justification

Neede connectivity to drewdeog to test new api

### PrivateLink Consumer YAML

```yaml
security_group:
  request_id: YOUR-REQUEST-ID
  business_justification: >
    YOUR BUSINESS JUSTIFICATION HERE
  accountId: 6666666
  region: us-east-1  # or us-west-2
  vpc_id: vpc-0f0330876868cc9d2  # or vpc-014a623d564aa2524
  serviceType: privatelink-consumer
  serviceName: YOUR-SERVICE-NAME
  thirdpartyName: YOUR-THIRD-PARTY-NAME
  thirdPartyID: YOUR-THIRD-PARTY-ID
rules:
  - request_id: YOUR-REQUEST-ID
    business_justification: >
        YOUR RULE JUSTIFICATION HERE
    source:
      account_id: YOUR-SOURCE-ACCOUNT-ID
      vpc_id: YOUR-SOURCE-VPC-ID
      region: YOUR-SOURCE-REGION
      ips:
        - 10.0.0.1/32
        - 10.0.0.2/32
    protocol: tcp
    port: 443
    appid: ssl
    url: https://your-service-url.com
    enable_palo_inspection: true
```
