### ISSUE TITLE
[SG] Create PrivateLink Consumer for: drewdogyaml

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#209]
### AWS Region

us-east-1

### PrivateLink Consumer YAML

```yaml
security_group:
  request_id: RQ-009
  business_justification: >
    Need drewdogyaml connectivity
  accountId: 6666666
  region: us-east-1
  vpc_id: vpc-0f0330876868cc9d2
  serviceType: privatelink-consumer
  serviceName: com.amazonaws.vpce.us-east-1.vpce-svc-064ea718f8d0ead77
  thirdpartyName: drewdogyaml
  thirdPartyID: 77777777
rules:
  - request_id: RQ-009
    business_justification: >
        Need drewdogyaml connectivity
    source:
      account_id: 12312312321
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.0.0.1/32
        - 10.0.0.2/32
    protocol: tcp
    port: 443
    appid: ssl
    url: https://drewdogyaml.com
    enable_palo_inspection: true
security_group:
  request_id: RQ-009
  business_justification: >
    Need drewdogyaml connectivity
  accountId: 6666666
  region: us-west-2
  vpc_id: vpc-014a623d564aa2524
  serviceType: privatelink-consumer
  serviceName: com.amazonaws.vpce.us-west-2.vpce-svc-064esd338d0ead77
  thirdpartyName: drewdogyaml
  thirdPartyID: 77777777
rules:
  - request_id: RQ-009
    business_justification: >
        Need drewdogyaml connectivity
    source:
      account_id: 12312312321
      vpc_id: vpc-aaa
      region: us-west-2
      ips:
        - 10.0.0.1/32
        - 10.0.0.2/32
    protocol: tcp
    port: 443
    appid: ssl
    url: https://drewdogyaml.com
    enable_palo_inspection: true
```
