### ISSUE TITLE
[SG] Create PrivateLink Consumer for: singleyamlcompany

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#235]
### AWS Region

us-east-1

### PrivateLink Consumer YAML

```yaml
security_group:
  request_id: RQ-0666
  business_justification: >
    Testing singleyamlcompany
  accountId: 23442342
  region: us-east-1
  vpc_id: vpc-0f0330876868cc9d2
  serviceType: privatelink-consumer
  serviceName: com.amazonaws.vpce.us-east-1.vpce-svc-064ea718f8d0ead77
  thirdpartyName: singleyamlcompany
  thirdPartyID: 123123123
rules:
  - request_id: RQ-0666
    business_justification: >
        Testing singleyamlcompany
    source:
      account_id: 1231231231
      vpc_id: vpc-cccc
      region: us-east-1
      ips:
        - 10.0.0.1/32
        - 10.0.0.2/32
    protocol: tcp
    port: 443
    appid: ssl
    url: https://your-service-url.com
    enable_palo_inspection: true
```
