### ISSUE TITLE
[SG] Create PrivateLink Consumer for:

### ISSUE THREAD

**Issue by drewpypro** [drewpypro/terraform-aws-netsec-automation#277]
### AWS Region

us-east-1

### PrivateLink Consumer YAML

```yaml
security_group:
  request_id: RQ-001
  business_justification: >
    Create security-group for datadog API us-east-1 privatelink in us-east-1
  accountId: 6666666
  region: us-east-1
  vpc_id: vpc-01f1d91e68dfc051f
  serviceType: privatelink-consumer
  serviceName: com.amazonaws.vpce.us-east-1.vpce-svc-064ea718f8d0ead77
  thirdpartyName: multi-rule-testing1
  thirdPartyID: 123456
rules:
  - request_id: RQ-001
    business_justification: >
        Create access from acct-1 intranet nat gateway to datadog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.50.0.0/24
    protocol: tcp
    port: 443
    appid: mongodb
    url: https://api.datadoghq.com
    enable_palo_inspection: true
  - request_id: RQ-002
    business_justification: >
        Create access from acct-1 intranet nat gateway to datadog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.58.1.1/32
    protocol: tcp
    port: 443
    appid: ssl
    url: https://api.datadoghq.com
    enable_palo_inspection: true
  - request_id: RQ-004454
    business_justification: >
        Create access from acct-1 intranet nat gateway to datadog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.50.0.0/24
    protocol: tcp
    port: 443
    appid: ssl
    url: https://logging.datadoghq.com
    enable_palo_inspection: true
  - request_id: RQ-002
    business_justification: >
        Create access from acct-1 intranet nat gateway to datadog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.58.1.1/32
    protocol: tcp
    port: 27017
    appid: mongodb
    url: 
    enable_palo_inspection: true
  - request_id: RQ-002
    business_justification: >
        Create access from acct-1 intranet nat gateway to datadog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.58.1.1/32
    protocol: tcp
    port: 27017
    appid:
    url: 
    enable_palo_inspection: true

```
